#!/usr/bin/env bash
#ITSTIMETOTELLTHETIME
hour=0
minute=1
while (( hour <= 12 )); do
while (( minute <= 59 )); do
echo "$minute"
(( minute++ ))
if (( minute > 59 )); then
       echo "Hour:$hour"
(( hour++ ))       
minute=1
fi
done
minute=1
done

