#!/usr/bin/env bash
# Loop through each item in the current directory
LIST=$(ls -1A)
for file in $LIST
do
    # Check if the file name contains a dash
    if [[ $file == *-* ]] ; then
        # Display the part of the name after the first dash
        echo "${file#*-}"
else
       echo "$LIST"
    fi
done
