#!/usr/bin/bash
# Loop through each item in the current directory
for item in./*; do
    # Check if the item is a file and does not start with a dot
    if [ -f "$item" ] ; [[! $item == \.* ]]; then
        # Extract the part of the name after the first dash
        name_after_dash=$(echo "$item" | sed -n 's/^.*-\(.*\)/\1/p')
        echo "$name_after_dash"
    fi
done

