#!/usr/bin/env bash
#This script checks if a file named school exists and if its full or empty
file="school"
if [ -e "$file" ]; then
echo "school file exists"

else
	echo "school file does not exist"
if [[ -s $file ]]; then
	echo "school file exists"
echo "school file is not empty"
echo "school is a regular file"
else
	echo "school file exists"
echo "school file is empty"
fi
if [[ -f $file ]]; then
	echo "school file exists"
	echo "school is a regular file"
else
	" "
fi
