#!/usr/bin/env bash
#This script checks if a file named school exists and if its full or empty
file="school"
if [ -f "$file" ]; then
if [ -s "$file" ]; then
echo "school file exists"
echo "school file is not empty"
echo "school is a regular file"
else
echo "school file exists"
echo "school file is empty"
fi
else
echo "school file does not exist"
fi
